#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag docker-robot-framework:ci christophettat/devops_coe_robot:"$TRAVIS_JOB_ID"
docker push christophettat/devops_coe_robot:"$TRAVIS_JOB_ID"
